import Foundation
import AppKit
import CryptoKit

public enum ClipKind: String, Codable, CaseIterable {
    case text, link, email, color, image, screenshot, video, file
    public var title: String { switch self { case .text: return "Text"; case .link: return "Links"; case .email: return "Emails"; case .color: return "Colors"; case .image: return "Images"; case .screenshot: return "Screenshots"; case .video: return "Videos"; case .file: return "Files" } }
    public var symbol: String { switch self { case .text: return "text.alignleft"; case .link: return "link"; case .email: return "at"; case .color: return "paintpalette"; case .image: return "photo"; case .screenshot: return "camera.viewfinder"; case .video: return "play.rectangle"; case .file: return "doc" } }
    public static func classify(_ value: String) -> ClipKind {
        let s = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.range(of: "^#(?:[A-Fa-f0-9]{3}|[A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$", options: .regularExpression) != nil { return .color }
        if s.range(of: "^[A-Z0-9._%+\\-]+@[A-Z0-9.\\-]+\\.[A-Z]{2,}$", options: [.regularExpression, .caseInsensitive]) != nil { return .email }
        if let url = URL(string: s), ["http", "https"].contains(url.scheme?.lowercased() ?? ""), url.host != nil, !s.contains(where: { $0.isWhitespace }) { return .link }
        return .text
    }
}

public struct Clip: Codable, Identifiable, Equatable {
    public var id: UUID
    public var createdAt: Date
    public var sourceName: String
    public var sourceBundle: String
    public let kind: ClipKind
    public let text: String
    public var pinned: Bool
    public let items: [[String: Data]]
    public let fingerprint: String
    public init(id: UUID = UUID(), createdAt: Date = Date(), sourceName: String, sourceBundle: String = "", kind: ClipKind, text: String, pinned: Bool = false, items: [[String: Data]] = []) {
        self.id = id; self.createdAt = createdAt; self.sourceName = sourceName; self.sourceBundle = sourceBundle; self.kind = kind; self.text = text; self.pinned = pinned; self.items = items
        self.fingerprint = Self.makeFingerprint(kind: kind, text: text, items: items)
    }
    public var title: String { text.split(whereSeparator: \.isNewline).first.map(String.init) ?? kind.title }
    public var byteCount: Int { items.reduce(0) { $0 + $1.values.reduce(0) { $0 + $1.count } } }
    private static func makeFingerprint(kind: ClipKind, text: String, items: [[String: Data]]) -> String {
        var hash = SHA256()
        hash.update(data: Data(kind.rawValue.utf8))
        hash.update(data: Data(text.utf8))
        for item in items { hash.update(data: Data([0])); for key in item.keys.sorted() { hash.update(data: Data(key.utf8)); hash.update(data: item[key]!) } }
        return hash.finalize().map { String(format: "%02x", $0) }.joined()
    }
    public var image: NSImage? { for item in items { for key in [NSPasteboard.PasteboardType.png.rawValue, NSPasteboard.PasteboardType.tiff.rawValue] { if let data = item[key], let image = NSImage(data: data) { return image } } }; return nil }
    public var fileURLs: [URL] { items.compactMap { item in guard let data = item[NSPasteboard.PasteboardType.fileURL.rawValue], let s = String(data: data, encoding: .utf8) else { return nil }; return URL(string: s) } }
    public func matches(_ query: String) -> Bool {
        let terms = query.split(whereSeparator: \.isWhitespace)
        guard !terms.isEmpty else { return true }
        let searchable = text + " " + sourceName + " " + kind.title + " " + (linkPresentation.map { $0.title + " " + $0.label } ?? "")
        return terms.allSatisfy { searchable.localizedStandardContains(String($0)) }
    }
}

public enum ClipboardCodec {
    public static let blockedTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.RestoredType", "com.agilebits.onepassword", "com.apple.is-remote-clipboard"]
    public static let defaultExclusions: Set<String> = ["com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "com.apple.Passwords", "com.apple.keychainaccess", "com.dashlane.Dashlane", "org.keepassxc.keepassxc"]
    public static func capture(_ board: NSPasteboard, sourceName: String, sourceBundle: String, excluded: Set<String> = defaultExclusions) -> Clip? {
        guard !excluded.contains(sourceBundle) else { return nil }
        let types = Set((board.types ?? []).map(\.rawValue))
        guard blockedTypes.isDisjoint(with: types) else { return nil }
        let safeTypes: Set<String> = Set([NSPasteboard.PasteboardType.string, .rtf, .rtfd, .html, .png, .tiff, .fileURL, .URL].map(\.rawValue))
        var total = 0
        var payload: [[String: Data]] = []
        for item in board.pasteboardItems ?? [] {
            guard blockedTypes.isDisjoint(with: Set(item.types.map(\.rawValue))) else { return nil }
            var representations: [String: Data] = [:]
            for type in item.types where safeTypes.contains(type.rawValue) {
                if let data = item.data(forType: type) {
                    total += data.count
                    guard total <= 20 * 1024 * 1024 else { return nil }
                    representations[type.rawValue] = data
                }
            }
            if !representations.isEmpty { payload.append(representations) }
        }
        guard !payload.isEmpty else { return nil }
        if (types.contains("com.apple.screencapture") || ["com.apple.screencapture", "com.apple.screencaptureui"].contains(sourceBundle)),
           let data = payload.first?[NSPasteboard.PasteboardType.png.rawValue] ?? payload.first?[NSPasteboard.PasteboardType.tiff.rawValue],
           let screenshot = ScreenshotCapture.clip(data: data) { return screenshot }
        if payload.count == 1, let data = payload.first?[NSPasteboard.PasteboardType.fileURL.rawValue],
           let path = String(data: data, encoding: .utf8), let url = URL(string: path),
           let screenshot = ScreenshotCapture.load(url) { return screenshot }
        var text = board.string(forType: .string) ?? board.string(forType: .URL) ?? ""
        var kind = ClipKind.classify(text)
        let files = payload.compactMap { $0[NSPasteboard.PasteboardType.fileURL.rawValue] }.compactMap { String(data: $0, encoding: .utf8) }.compactMap(URL.init(string:))
        if !files.isEmpty {
            kind = files.allSatisfy { ["mov", "mp4", "m4v", "webm", "avi"].contains($0.pathExtension.lowercased()) } ? .video : .file
            text = files.map(\.lastPathComponent).joined(separator: "\n")
        } else if types.contains(NSPasteboard.PasteboardType.png.rawValue) || types.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            kind = .image; text = "Copied image"
        }
        guard !text.isEmpty || kind == .image else { return nil }
        return Clip(sourceName: sourceName, sourceBundle: sourceBundle, kind: kind, text: text, items: payload)
    }
    @discardableResult public static func restore(_ clip: Clip, to board: NSPasteboard, plainText: Bool = false) -> Bool {
        board.clearContents()
        if plainText || clip.items.isEmpty { return board.setString(clip.text, forType: .string) }
        let items = clip.items.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            if clip.kind == .screenshot { item.setData(Data(), forType: NSPasteboard.PasteboardType("com.apple.screencapture")) }
            return item
        }
        return board.writeObjects(items)
    }
}

public struct History: Codable {
    public var clips: [Clip] = []
    public init(clips: [Clip] = []) { self.clips = clips }
    public mutating func insert(_ clip: Clip, limit: Int = 500) {
        // A clipboard-only capture can arrive without a screenshot marker. Merge
        // matching image pixels when the file watcher identifies that same capture.
        if clip.kind == .screenshot || clip.kind == .image,
           let data = clip.items.first?[NSPasteboard.PasteboardType.png.rawValue] ?? clip.items.first?[NSPasteboard.PasteboardType.tiff.rawValue] {
            let candidates = clips.indices.filter {
                (clips[$0].kind == .screenshot || clips[$0].kind == .image) &&
                clips[$0].kind != clip.kind && abs(clips[$0].createdAt.timeIntervalSince(clip.createdAt)) < 15
            }
            if !candidates.isEmpty, let normalized = ScreenshotCapture.clip(data: data),
               let index = candidates.first(where: { index in
                   guard let other = clips[index].items.first?[NSPasteboard.PasteboardType.png.rawValue] ?? clips[index].items.first?[NSPasteboard.PasteboardType.tiff.rawValue] else { return false }
                   return ScreenshotCapture.clip(data: other)?.fingerprint == normalized.fingerprint
               }) {
                let existing = clips.remove(at: index)
                let merged = Clip(id: existing.id, createdAt: max(existing.createdAt, clip.createdAt), sourceName: "Screenshot", sourceBundle: "com.apple.screencapture", kind: .screenshot, text: normalized.text, pinned: existing.pinned || clip.pinned, items: normalized.items)
                insert(merged, limit: limit)
                return
            }
        }
        let fingerprint = clip.fingerprint
        if let index = clips.firstIndex(where: { $0.fingerprint == fingerprint }) {
            var existing = clips.remove(at: index)
            existing.createdAt = clip.createdAt; existing.sourceName = clip.sourceName; existing.sourceBundle = clip.sourceBundle
            clips.insert(existing, at: 0)
        } else { clips.insert(clip, at: 0) }
        var unpinned = 0
        clips = clips.filter { if $0.pinned { return true }; unpinned += 1; return unpinned <= limit }
        var bytes = clips.reduce(0) { $0 + $1.byteCount }
        while bytes > 200 * 1024 * 1024, let index = clips.lastIndex(where: { !$0.pinned }) { bytes -= clips.remove(at: index).byteCount }
    }
    public mutating func expire(days: Int, now: Date = Date()) { guard days > 0 else { return }; let cutoff = now.addingTimeInterval(-Double(days) * 86400); clips.removeAll { !$0.pinned && $0.createdAt < cutoff } }
    public func filtered(query: String, kind: ClipKind? = nil, pinnedOnly: Bool = false) -> [Clip] {
        clips.filter { (kind == nil || $0.kind == kind) && (!pinnedOnly || $0.pinned) && $0.matches(query) }.sorted { if $0.pinned != $1.pinned { return $0.pinned }; return $0.createdAt > $1.createdAt }
    }
}

public enum HistoryDisk {
    public static func load(from url: URL) throws -> History { guard FileManager.default.fileExists(atPath: url.path) else { return History() }; return try JSONDecoder().decode(History.self, from: Data(contentsOf: url)) }
    public static func save(_ history: History, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        let data = try JSONEncoder().encode(history)
        try data.write(to: url, options: .atomic)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}
