import Foundation
import AppKit

public enum ClipboardCodec {
    public static let maximumBytes = 20 * 1024 * 1024
    private static let safeTypes = Set(
        [NSPasteboard.PasteboardType.string, .rtf, .rtfd, .html, .png, .tiff, .fileURL, .URL].map(\.rawValue))
    public static let blockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.RestoredType", "com.agilebits.onepassword",
        "com.apple.is-remote-clipboard",
    ]
    public static let defaultExclusions: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop",
        "com.apple.Passwords", "com.apple.keychainaccess", "com.dashlane.Dashlane", "org.keepassxc.keepassxc",
    ]
    public static func capture(
        _ board: NSPasteboard, sourceName: String, sourceBundle: String,
        excluded: Set<String> = defaultExclusions
    ) -> Clip? {
        guard !excluded.contains(sourceBundle) else { return nil }
        let types = Set((board.types ?? []).map(\.rawValue))
        guard blockedTypes.isDisjoint(with: types) else { return nil }
        var total = 0
        var payload: [[String: Data]] = []
        for item in board.pasteboardItems ?? [] {
            guard blockedTypes.isDisjoint(with: Set(item.types.map(\.rawValue))) else { return nil }
            var representations: [String: Data] = [:]
            for type in item.types where safeTypes.contains(type.rawValue) {
                if let data = item.data(forType: type) {
                    total += data.count
                    guard total <= maximumBytes else { return nil }
                    representations[type.rawValue] = data
                }
            }
            if !representations.isEmpty { payload.append(representations) }
        }
        guard !payload.isEmpty else { return nil }
        if (types.contains("com.apple.screencapture")
            || ["com.apple.screencapture", "com.apple.screencaptureui"].contains(sourceBundle)),
            let data = payload.first?[NSPasteboard.PasteboardType.png.rawValue]
                ?? payload.first?[NSPasteboard.PasteboardType.tiff.rawValue],
            let screenshot = ScreenshotCapture.clip(data: data)
        {
            return screenshot
        }
        if payload.count == 1, let data = payload.first?[NSPasteboard.PasteboardType.fileURL.rawValue],
            let path = String(data: data, encoding: .utf8), let url = URL(string: path),
            let screenshot = ScreenshotCapture.load(url)
        {
            return screenshot
        }
        var text = board.string(forType: .string) ?? board.string(forType: .URL) ?? ""
        var kind = ClipKind.classify(text)
        let files = payload.compactMap { $0[NSPasteboard.PasteboardType.fileURL.rawValue] }.compactMap {
            String(data: $0, encoding: .utf8)
        }.compactMap(URL.init(string:))
        if !files.isEmpty {
            kind =
                files.allSatisfy {
                    ["mov", "mp4", "m4v", "webm", "avi"].contains($0.pathExtension.lowercased())
                } ? .video : .file
            text = files.map(\.lastPathComponent).joined(separator: "\n")
        } else if types.contains(NSPasteboard.PasteboardType.png.rawValue)
            || types.contains(NSPasteboard.PasteboardType.tiff.rawValue)
        {
            kind = .image
            text = "Copied image"
        }
        guard !text.isEmpty || kind == .image else { return nil }
        return Clip(
            sourceName: sourceName, sourceBundle: sourceBundle, kind: kind, text: text, items: payload)
    }
    @discardableResult public static func restore(
        _ clip: Clip, to board: NSPasteboard, plainText: Bool = false
    ) -> Bool {
        board.clearContents()
        if plainText || clip.items.isEmpty { return board.setString(clip.text, forType: .string) }
        let items = clip.items.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            if clip.kind == .screenshot {
                item.setData(Data(), forType: NSPasteboard.PasteboardType("com.apple.screencapture"))
            }
            return item
        }
        return board.writeObjects(items)
    }
}
